"use client";
import { useEffect, useRef, useState } from 'react';
import { download, normalizePhoto } from '@/lib/aip/client';
import { loadPhoto } from '@/lib/aip/photo-composite';
export default function OutcomeComparison({src,uploaded}:{src:string;uploaded:boolean}){
 const [followup,setFollowup]=useState(''),[baselineDate,setBaselineDate]=useState(''),[followupDate,setFollowupDate]=useState(''),[notes,setNotes]=useState(''),[consent,setConsent]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const file=useRef<HTMLInputElement>(null),version=useRef(0);
 useEffect(()=>{version.current++;setFollowup('');setBaselineDate('');setFollowupDate('');setNotes('');setConsent(false);setError('');return()=>{version.current++;};},[src]);
 useEffect(()=>()=>{if(followup)URL.revokeObjectURL(followup);},[followup]);
 async function choose(f?:File){if(!f||!consent)return;const v=version.current;try{const b=await normalizePhoto(f);if(v!==version.current)return;setFollowup(URL.createObjectURL(b));setError('');}catch(e){if(v===version.current)setError((e as Error).message);}}
 async function exportComparison(){if(!followup||!baselineDate||!followupDate||busy)return;if(followupDate<baselineDate){setError('The follow-up date must be on or after the baseline date.');return;}setBusy(true);const v=version.current;
 try{const [a,b]=await Promise.all([loadPhoto(src),loadPhoto(followup)]);if(v!==version.current)return;const c=document.createElement('canvas');c.width=1600;c.height=1180;const ctx=c.getContext('2d')!;ctx.fillStyle='#101f1b';ctx.fillRect(0,0,c.width,c.height);[a,b].forEach((img,i)=>{const scale=Math.min(760/img.width,990/img.height),w=img.width*scale,h=img.height*scale;ctx.drawImage(img,20+i*800+(760-w)/2,80+(990-h)/2,w,h);});ctx.fillStyle='#d3ecdf';ctx.font='22px sans-serif';ctx.fillText(`Baseline · ${baselineDate}`,25,45);ctx.fillText(`Follow-up · ${followupDate}`,825,45);ctx.font='19px sans-serif';ctx.fillText('AIP / Recorded photographs · No simulated edits · Capture conditions may differ',25,1110);const blob=await new Promise<Blob|null>(r=>c.toBlob(r,'image/jpeg',.94));if(blob&&v===version.current){download(blob,'aip-recorded-comparison.jpg');download(new Blob([JSON.stringify({baselineDate,followupDate,notes,kind:'Recorded photographs, not a predicted treatment outcome'},null,2)],{type:'application/json'}),'aip-comparison-notes.json');}}catch(e){if(v===version.current)setError((e as Error).message);}finally{setBusy(false);}}
 if(!uploaded)return <section className="panel outcome-panel"><p className="eyebrow">CLINICAL STUDIO / RECORDED OUTCOMES</p><h2>Compare what actually changed.</h2><p className="muted">Upload the person’s baseline portrait in Discover to unlock real follow-up comparison, capture dates, observations and export. Fictional samples cannot be used as recorded clinical baselines.</p></section>;
 return <section className="panel outcome-panel"><p className="eyebrow">CLINICAL STUDIO / RECORDED OUTCOMES</p><h2>Compare what actually changed.</h2><p className="muted">Place a follow-up photograph beside the unedited baseline. Match lighting, pose, expression and camera distance before interpreting differences.</p><div className="outcome-pair"><figure><img src={src} alt="Unedited baseline portrait"/><figcaption>Baseline · original photograph</figcaption></figure><figure>{followup?<img src={followup} alt="Actual uploaded follow-up, without simulated changes"/>:<div className="outcome-empty">Add a real follow-up photograph to compare.</div>}<figcaption>Follow-up · recorded appearance</figcaption></figure></div>
 <div className="outcome-toolbar"><label className="form-field">Baseline date<input type="date" value={baselineDate} onChange={e=>setBaselineDate(e.target.value)}/></label><label className="form-field">Follow-up date<input type="date" min={baselineDate} value={followupDate} onChange={e=>setFollowupDate(e.target.value)}/></label></div>
 <label className="consent-row"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>I confirm these are photographs of the same consenting adult.</span></label><input className="sr-only" ref={file} type="file" accept="image/jpeg,image/png,image/webp" aria-label="Upload actual follow-up photograph" onChange={e=>{void choose(e.target.files?.[0]);e.target.value='';}}/>
 <div className="outcome-toolbar"><button className="secondary-button" disabled={!consent} onClick={()=>file.current?.click()}>{followup?'Replace follow-up':'Add follow-up photo'}</button>{followup&&<button className="text-link" onClick={()=>setFollowup('')}>Remove follow-up</button>}</div>
 <label className="form-field">Observations and capture conditions<textarea maxLength={2000} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Document expression, lighting differences and observations."/></label><button className="secondary-button" disabled={!followup||!baselineDate||!followupDate||busy} onClick={exportComparison}>{busy?'Preparing…':'Export photographs & notes'}</button>{error&&<p className="form-error" role="alert">{error}</p>}<p className="micro-copy">Session only · export before leaving. No automatic outcome score, dose recommendation or model training. Photography alone does not establish treatment causation.</p></section>;
}
